### ISSUE TITLE
Help getting USPS API Key

### ISSUE THREAD

**Issue by huntersgordon** [LiterallyLarry/USPS-Tracking-Python#4]
Hello, I signed up with USPS's web tools API, and they sent the username and password to my email— yet I see nothing about how I can obtain an API key. Please guide me to the next steps

**Comment by LiterallyLarry** [comment]
You should be able to use the Web Tools User ID (Username) listed in the registration e-mail as the API key.

**Comment by huntersgordon** [comment]
Thanks @LiterallyLarry , for the quick response and easy fix!
